tempo:
  metricsGenerator:
    enabled: true
    remoteWriteUrl: http://prometheus-prometheus.monitoring.svc.cluster.local:9090/api/v1/write

serviceMonitor:
  enabled: true
  additionalLabels:
    release: prometheus
  interval: 30s